old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            vhost:    '/'
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
    producers:
        blast:
            connection:       default
            exchange_options: {name: 'blast', type: direct}
            enable_logger: true
        multiple_alignment:
            connection:       default
            exchange_options: {name: 'multiple-alignment', type: direct}
            enable_logger: true
    consumers:
        blast:
            connection:       default
            exchange_options: {name: 'blast', type: direct}
            queue_options:    {name: 'blast'}
            callback:         App\Consumer\BlastConsumer
            qos_options:      {prefetch_size: 0, prefetch_count: 1, global: false}
            enable_logger: true
        multiple_alignment:
            connection:       default
            exchange_options: {name: 'multiple-alignment', type: direct}
            queue_options:    {name: 'multiple-alignment'}
            callback:         App\Consumer\MultipleAlignmentConsumer
            qos_options:      {prefetch_size: 0, prefetch_count: 1, global: false}
            enable_logger: true
