version: '3.2'

services:
    app:
        image: ${APP_DOCKER_IMAGE_NAME}:${APP_DEV_DOCKER_IMAGE_TAG}
        environment:
            - SYMFONY_ENV=test
        build:
            cache_from:
                - ${APP_DOCKER_IMAGE_NAME}:${APP_DEV_DOCKER_IMAGE_TAG}
                - ${APP_DOCKER_IMAGE_NAME}:dev
