version: '2'

services:
    nginx:
        container_name: grycii-nginx
        ports:
            - 127.0.0.1:8082:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - .:/var/www/html:ro

    app:
        container_name: grycii-app
        volumes:
            - .:/var/www/html:rw

    redis:
        container_name: grycii-redis

    db:
        container_name: grycii-db
        environment:
            - MYSQL_ROOT_PASSWORD=grycii
            - MYSQL_USER=grycii
            - MYSQL_PASSWORD=grycii
            - MYSQL_DATABASE=grycii
        ports:
            - 127.0.0.1:3308:3306

    es:
        container_name: grycii-elasticsearch
        ports:
            - 127.0.0.1:9200:9200
            - 127.0.0.1:9300:9300
        volumes:
            - es1_data:/usr/share/elasticsearch/data
            - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

    es-head:
        container_name: grycii-elasticsearch-head
        image: mobz/elasticsearch-head:5
        ports:
            - 127.0.0.1:9100:9100
        networks:
            - default

    rabbitmq:
        container_name: grycii-rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=grycii
            - RABBITMQ_DEFAULT_PASS=grycii
        ports:
            - 127.0.0.1:15672:15672
