version: '3.4'

services:
    app:
        build:
            context: .
            target: app-dev
            cache_from:
            - ${APP_DEV_IMAGE_NAME}:${APP_DEV_IMAGE_TAG}
            - ${APP_DEV_IMAGE_NAME}:latest
        volumes:
        - .:/app
