<?php

namespace AppBundle\Repository;

/**
 * BlastFileRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlastFileRepository extends \Doctrine\ORM\EntityRepository
{
}
