<?php

namespace AppBundle\Repository;

/**
 * BlastRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlastRepository extends \Doctrine\ORM\EntityRepository
{
    public function findExpiredBlasts()
    {
        $date = new \DateTime();
        $date->modify('-1 day');

        $query = $this->createQueryBuilder('blast')
            ->where('blast.created < :date')
                ->setParameter('date', $date)
            ->getQuery();

        return $query->getResult();
    }

    public function findToBlast($id)
    {
        $query = $this->createQueryBuilder('blast')
            ->leftJoin('blast.strains', 'strains')
                ->addSelect('strains')
            ->where('blast.id = :id')
                ->setParameter('id', $id)
            ->getquery();

        return $query->getOneOrNullResult();
    }
}
