<?php

namespace AppBundle\Repository;

/**
 * ChromosomeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChromosomeRepository extends \Doctrine\ORM\EntityRepository
{
}
