<?php

namespace AppBundle\Repository;

/**
 * ChromosomeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChromosomeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChromosomeWithStrainAndSpecies($slug) {
        $query = $this
            ->createQueryBuilder('c')
            ->leftJoin('c.seos', 'seos')
                ->addSelect('seos')
            ->leftJoin('c.strain', 'strain')
                ->addSelect('strain')
            ->leftJoin('strain.species', 'species')
                ->addSelect('species')
            ->where('c.slug = :slug')
                ->setParameter('slug', $slug)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
