<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * CladeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CladeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCladesWithSpecies()
    {
        $query = $this
            ->createQueryBuilder('clade')
            ->leftJoin('clade.species', 'species')
                ->addSelect('species')
            ->orderBy('clade.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }

    public function getAvailableStrains(User $user = null)
    {
        $query = $this->createQueryBuilder('clade')
            ->leftJoin('clade.species', 'species')
                ->addSelect('species')
            ->leftJoin('species.strains', 'strains')
                ->addSelect('strains')
            ->leftJoin('strains.users', 'users')
            ->orderBy('clade.name', 'asc')
            ->addOrderBy('species.scientificName', 'asc')
            ->addOrderBy('strains.name', 'asc')
            ->where('strains.public = true')
            ->orWhere('users = :user')
                ->setParameter('user', $user)
            ->getQuery();

        return $query->getResult();
    }
}
