<?php

namespace Grycii\AppBundle\Repository;

/**
 * CladeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CladeRepository extends \Doctrine\ORM\EntityRepository
{
}
