<?php

namespace AppBundle\Repository;

/**
 * CladeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CladeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCladesWithSpecies()
    {
        $query = $this
            ->createQueryBuilder('clade')
            ->leftJoin('clade.species', 'species')
                ->addSelect('species')
            ->orderBy('clade.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
