<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ContactUsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactUsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMessages($page, $nbPerPage)
    {
        $query = $this
            ->createQueryBuilder('m')
            ->leftJoin('m.category', 'c')
                ->addSelect('c')
            ->orderBy('m.date', 'ASC')
            ->getQuery();

        $query
            ->setFirstResult(($page - 1) * $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }

    public function getNumberMessages()
    {
        return $this
            ->createQueryBuilder('m')
            ->select('COUNT(m)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
