<?php

namespace AppBundle\Repository;

/**
 * ContactUsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactUsCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
