<?php

namespace AppBundle\Repository;

/**
 * ContactUsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactUsRepository extends \Doctrine\ORM\EntityRepository
{
}
