<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ContactUs;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ContactUsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactUsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMessages($page)
    {
        $query = $this
            ->createQueryBuilder('contact_us')
            ->orderBy('contact_us.date', 'ASC')
            ->getQuery();

        $query
            ->setFirstResult(($page - 1) * ContactUs::NUM_ITEMS)
            ->setMaxResults(ContactUs::NUM_ITEMS);

        return new Paginator($query, true);
    }

    public function getNumberMessages()
    {
        return $this
            ->createQueryBuilder('m')
            ->select('COUNT(m)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
