<?php

namespace AppBundle\Repository;

/**
 * DbxrefRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DbxrefRepository extends \Doctrine\ORM\EntityRepository
{
}
