<?php

namespace AppBundle\Repository;

/**
 * FlatFileRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatFileRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByFeatureMolChromosomeFormat($featureType, $molType, $chromosome, $format)
    {
        $query = $this
            ->createQueryBuilder('flatFile')
            ->leftJoin('flatFile.chromosome', 'chromosome')
                ->where('flatFile.featureType = :featureType')
                ->andWhere('flatFile.molType = :molType')
                ->andWhere('flatFile.format = :format')
                ->andWhere('chromosome.name = :chromosome')
                ->setParameters([
                    'featureType' => $featureType,
                    'molType'     => $molType,
                    'format'      => $format,
                    'chromosome'  => $chromosome,
                ])
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    public function findByStrainFeatureMolFormat($strain, $featureType, $molType, $format)
    {
        $query = $this
            ->createQueryBuilder('flatFile')
            ->leftJoin('flatFile.chromosome', 'chromosome')
            ->leftJoin('chromosome.strain', 'strain')
            ->where('flatFile.featureType = :featureType')
            ->andWhere('flatFile.molType = :molType')
            ->andWhere('flatFile.format = :format')
            ->andWhere('strain.name = :strain')
            ->setParameters([
                'featureType' => $featureType,
                'molType'     => $molType,
                'format'      => $format,
                'strain'      => $strain,
            ])
            ->getQuery();

        return $query->getResult();
    }
}
