<?php

namespace AppBundle\Repository;

/**
 * FlatFileRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatFileRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $strain
     * @param $type
     *
     * @return array
     */
    public function findByStrainAndType($strain, $type)
    {
        $query = $this
            ->createQueryBuilder('flatFile')
            ->leftJoin('flatFile.chromosome', 'chromosome')
            ->leftJoin('chromosome.strain', 'strain')
            ->where('strain.name = :strain')
            ->andWhere('flatFile.type = :type')
            ->setParameters([
                'strain' => $strain,
                'type' => $type,
            ])
            ->getQuery();

        return $query->getResult();
    }
}
