<?php
/**
 *    Copyright 2015-2018 Mathieu Piot
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

namespace AppBundle\Repository;

/**
 * FlatFileRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatFileRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $strain
     * @param $type
     *
     * @return array
     */
    public function findByStrainAndType($strain, $type)
    {
        $query = $this
            ->createQueryBuilder('flatFile')
            ->leftJoin('flatFile.chromosome', 'chromosome')
            ->leftJoin('chromosome.strain', 'strain')
            ->where('strain.name = :strain')
            ->andWhere('flatFile.type = :type')
            ->setParameters([
                'strain' => $strain,
                'type' => $type,
            ])
            ->getQuery();

        return $query->getResult();
    }
}
