<?php

namespace AppBundle\Repository;

/**
 * JobRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends \Doctrine\ORM\EntityRepository
{
    public function findExpiredJobs()
    {
        $date = new \DateTime();
        $date->modify('-1 day');

        $query = $this->createQueryBuilder('job')
            ->groupBy('job.createdBy')
            ->where('job.created < :date')
            ->setParameter('date', $date)
            ->getQuery();

        return $query->getResult();
    }
}
