<?php

namespace AppBundle\Repository;

/**
 * LocusRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocusRepository extends \Doctrine\ORM\EntityRepository
{
}
