<?php

namespace AppBundle\Repository;

/**
 * MultipleAlignmentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultipleAlignmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findExpired()
    {
        $date = new \DateTime();
        $date->modify('-1 day');

        $query = $this->createQueryBuilder('multiple_alignment')
            ->where('multiple_alignment.created < :date')
            ->setParameter('date', $date)
            ->getQuery();

        return $query->getResult();
    }
}
