<?php

namespace AppBundle\Repository;

/**
 * MultipleAlignmentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultipleAlignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
