<?php

namespace AppBundle\Repository;

/**
 * NeighbourRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeighbourRepository extends \Doctrine\ORM\EntityRepository
{
}
