<?php

namespace AppBundle\Repository;

/**
 * SpeciesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeciesRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Select all or a specific species with strains
     */
    public function getSpeciesWithStrains($slug = null)
    {
        $query = $this
            ->createQueryBuilder('species')
            ->leftJoin('species.strains', 'strain')
                ->addSelect('strain')
        ;

        if (null !== $slug) {
            return $query
                ->where('species.slug = :slug')
                ->setParameter('slug', $slug)
                ->leftJoin('species.seos', 'seos')
                    ->addSelect('seos')
                ->getQuery()
                ->getOneOrNullResult();

        } else {
            return $query
                ->orderBy('species.scientificName', 'ASC')
                ->getQuery()
                ->getResult();
        }
    }

}
