<?php

namespace AppBundle\Repository;

/**
 * StrainRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrainRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStrainWithSpeciesAndChromosomes($slug)
    {
        $query = $this
            ->createQueryBuilder('strain')
            ->where('strain.slug = :slug')
            ->setParameter('slug', $slug)
            ->leftJoin('strain.species', 'species')
                ->addSelect('species')
            ->leftJoin('strain.chromosomes', 'c')
                ->addSelect('c')
                ->orderBy('c.name', 'ASC')
            ->getQuery();

        return $query->getSingleResult();
    }

    public function getStrainWithFlatFiles($slug)
    {
        $query = $this
            ->createQueryBuilder('strain')
                ->where('strain.slug = :slug')
                ->setParameter('slug', $slug)
            ->leftJoin('strain.users', 'users')
                ->addSelect('users')
            ->leftJoin('strain.chromosomes', 'chromosomes')
                ->addSelect('chromosomes')
                ->orderBy('chromosomes.name', 'ASC')
            ->leftJoin('chromosomes.flatFiles', 'flatFiles')
                ->addSelect('flatFiles')
            ->leftJoin('strain.species', 'species')
                ->addSelect('species')
            ->leftJoin('strain.seos', 'seos')
                ->addSelect('seos')
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    public function getStrainsWithSpeciesAndClade()
    {
        $query = $this
            ->createQueryBuilder('strain')
            ->leftJoin('strain.species', 'species')
                ->addSelect('species')
            ->leftJoin('species.clade', 'clade')
                ->addSelect('clade')
            ->orderBy('species.scientificName', 'ASC')
            ->addOrderBy('strain.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
