<?php

namespace AppBundle\Repository;

/**
 * StrainRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrainRepository extends \Doctrine\ORM\EntityRepository
{
}
