#!/bin/bash

docker pull $APP_DOCKER_IMAGE_NAME:prod
docker build --cache-from=$APP_DOCKER_IMAGE_NAME:prod -t $APP_DOCKER_IMAGE_NAME:prod-$TRAVIS_TAG .
docker tag $APP_DOCKER_IMAGE_NAME:prod-$TRAVIS_TAG $APP_DOCKER_IMAGE_NAME:prod
docker push $APP_DOCKER_IMAGE_NAME:prod-$TRAVIS_TAG
docker push $APP_DOCKER_IMAGE_NAME:prod
